# Use an official Python runtime as a parent image
 FROM python:3.9-slim

# Set the working directory in the container
# WORKDIR /Healthy-Desk-

# Install any needed packages
# RUN pip install --no-cache-dir debugpy

# Copy the desk-simulator directory contents into the container at /Healthy-Desk-/desk-simulator
# COPY desk-simulator /Healthy-Desk-/desk-simulator

# Set the working directory to /Healthy-Desk-/desk-simulator
# WORKDIR /Healthy-Desk-/desk-simulator

# Expose port 8000 for the REST server
# EXPOSE 8000

# Start the server and the Python API service
# CMD ["python", "simulator/main.py", "--port", "8000"]
